apiVersion: 1

datasources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki:3100
      isDefault: true
      editable: false
      jsonData:
          maxLines: 1000

    - name: Prometheus
      uid: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: false
      editable: false

    - name: InfluxDB-JMeter
      uid: influxdb-jmeter
      type: influxdb
      access: proxy
      url: http://influxdb:8086
      database: jmeter
      isDefault: false
      editable: false
      jsonData:
          httpMode: GET
